-- MySQL Script generated by MySQL Workbench
-- 05/28/15 04:01:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facil` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `facil` ;

-- -----------------------------------------------------
-- Table `facil`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facil`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
